@startuml
title Godzilla Use Cases
'https://plantuml.com/use-case-diagram
left to right direction

skinparam actorStyle awesome

actor Godzilla << Server >>
note bottom of Godzilla
    Godzilla is Hosted in IIS or
    another web server.
end note

rectangle Browser{
    rectangle HTTP {
        usecase (GET Resource) as HttpGet
        usecase (POST Resource) as HttpPost
        usecase (PUT Resource) as HttpPut
        usecase (DELETE Resource) as HttpDelete
    }

    rectangle WebSocket {
        usecase (Read Resource) as ReadRes
        usecase (Save Resource) as SaveRes
        usecase (Remove Resource) as RemoveRes
        usecase (Send Notification) << Event >> as Notification
    }
}

Godzilla <=l= ReadRes
Godzilla <=l= SaveRes
Godzilla <=l= RemoveRes

Godzilla =d=> Notification

Godzilla <=u= HttpGet
Godzilla <=u= HttpPost
Godzilla <=u= HttpPut
Godzilla <=u= HttpDelete
@enduml